//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.EF_GLOBAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class cotizacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cotizacion()
        {
            this.detalle_cotizacion_productos = new HashSet<detalle_cotizacion_productos>();
        }
    
        public int idcotizacion { get; set; }
        public int idcliente { get; set; }
        public int idtrabajador { get; set; }
        public int cantidad { get; set; }
        public decimal subtotal { get; set; }
        public decimal itbis { get; set; }
        public decimal total { get; set; }
        public System.DateTime fecha { get; set; }
        public bool estatus { get; set; }
    
        public virtual cliente cliente { get; set; }
        public virtual trabajador trabajador { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_cotizacion_productos> detalle_cotizacion_productos { get; set; }
    }
}
