//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.EF_GLOBAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle_cotizacion_productos
    {
        public int id_cotizacion_producto { get; set; }
        public int idcotizacion { get; set; }
        public string producto { get; set; }
        public int cantidad { get; set; }
        public decimal precioVenta { get; set; }
        public decimal itbis { get; set; }
        public decimal subtotal { get; set; }
        public decimal total { get; set; }
    
        public virtual cotizacion cotizacion { get; set; }
    }
}
