//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.EF_GLOBAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura
    {
        public int id_factura { get; set; }
        public int id_cliente { get; set; }
        public string nombre_trabajador { get; set; }
        public string tipo_pago { get; set; }
        public System.DateTime fecha { get; set; }
        public string medio_pago { get; set; }
        public int id_venta { get; set; }
        public int id_trabajador { get; set; }
        public int cantidad_articulos { get; set; }
        public decimal subtotal { get; set; }
        public decimal itbis { get; set; }
        public decimal total { get; set; }
        public string numero_factura { get; set; }
    
        public virtual cliente cliente { get; set; }
        public virtual trabajador trabajador { get; set; }
        public virtual venta venta { get; set; }
    }
}
