//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.EF_GLOBAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ingreso
    {
        public int idingreso { get; set; }
        public Nullable<int> CodigBarra { get; set; }
        public int idproveedor { get; set; }
        public System.DateTime fecha { get; set; }
        public string tipo_comprobante { get; set; }
        public decimal igv { get; set; }
        public System.DateTime FechaAdiciona { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
        public string UsuarioAdiciona { get; set; }
        public string UsuarioModifica { get; set; }
    }
}
