//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.EF_GLOBAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class wv_usuario_trabajador
    {
        public int RolID { get; set; }
        public string NombreCompleto { get; set; }
        public string Clave { get; set; }
        public string Usuario { get; set; }
        public int idtrabajador { get; set; }
    }
}
