//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.EF_GLOBAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ciudad
    {
        public int CiudadID { get; set; }
        public string CiudadNombre { get; set; }
        public string PaisCodigo { get; set; }
        public string CiudadDistrito { get; set; }
        public int CiudadPoblacion { get; set; }
        public Nullable<int> id_pais { get; set; }
    }
}
