//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.EF_GLOBAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pais
    {
        public int id_pais { get; set; }
        public string PaisCodigo { get; set; }
        public string PaisNombre { get; set; }
        public string PaisContinente { get; set; }
        public string PaisRegion { get; set; }
        public double PaisArea { get; set; }
        public Nullable<short> PaisIndependencia { get; set; }
        public int PaisPoblacion { get; set; }
        public Nullable<double> PaisExpectativaDeVida { get; set; }
        public Nullable<double> PaisProductoInternoBruto { get; set; }
        public Nullable<double> PaisProductoInternoBrutoAntiguo { get; set; }
        public string PaisNombreLocal { get; set; }
        public string PaisGobierno { get; set; }
        public string PaisJefeDeEstado { get; set; }
        public Nullable<int> PaisCapital { get; set; }
        public string PaisCodigo2 { get; set; }
    }
}
