//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.EF_GLOBAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class wv_get_employees
    {
        public int idtrabajador { get; set; }
        public string NombreCompleto { get; set; }
        public string sexo { get; set; }
        public System.DateTime Fecha_nac { get; set; }
        public string num_documento { get; set; }
        public string direccion { get; set; }
        public string telefono { get; set; }
        public string email { get; set; }
        public string Estado { get; set; }
        public Nullable<System.DateTime> FechaAdiciona { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
        public string UsuarioAdiciona { get; set; }
        public string UsuarioModifica { get; set; }
    }
}
